image: Visual Studio 2017

environment:
  MICROPY_CPYTHON3: c:/python34/python.exe
  MICROPYPATH: c:/projects/micropython/ports/windows

init:
  # Set build version number to commit to be travis-like
- ps: Update-AppveyorBuild -Version $env:appveyor_repo_commit.substring(0,8)

configuration:
- Debug
- Release

platform:
- x86
- x64

build_script:
- cmd: >-
    git clone -q --depth 1 --branch=windows-pyd https://github.com/stinos/micropython ../micropython

    msbuild ../micropython/ports/windows/micropythoncore.vcxproj /p:platform=%platform%;configuration=%configuration%

    msbuild ../micropython/ports/windows/micropython.vcxproj /p:platform=%platform%;configuration=%configuration%

    msbuild micropython-wrap.vcxproj /p:platform=%platform%;configuration=%configuration%

test_script:
- cmd: >-
    %MICROPY_CPYTHON3% ../micropython/tests/run-tests --keep-path -d tests/py

on_failure:
- cmd: >-
    %MICROPY_CPYTHON3% ../micropython/tests/run-tests --print-failures

skip_tags: true

deploy: off

nuget:
  disable_publish_on_pr: true

matrix:
  fast_finish: true
